### PR TITLE
Add method to convert the screen tap point to pdf page coordinates

### PR DESCRIPTION
**Pull request by xiasenhai**
Convert the screen coordinates of a point to page coordinates.
tested with different sized pages([sample.pdf](https://github.com/barteksc/AndroidPdfViewer/blob/master/sample/src/main/assets/sample.pdf) from [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) repo)

**Add an Annotation where user tapped**
screenshot_1521560623

screenshot_1521560598

### CODE REVIEW

**Comment by SagarKhurana** [comment]
@xiasenhai 
Can you provide some more information on this PR? 
How we shall include it in the functionality to identify the user touch on the screen. 
Please refer my [issue ](https://github.com/barteksc/AndroidPdfViewer/issues/757)
Thanks

**Comment by benjinus** [comment]
@SagarKhurana i am xiasenhai. i post a reply on your [issue](https://github.com/barteksc/AndroidPdfViewer/issues/757).

**Comment by laurabarroso41** [comment]
@xiasenhai I need to use this functionality but I don't know where is placed. I am using the com.github.barteksc:android-pdf-viewer:3.2.0-beta.1 library. But this functionality is not there...I already take a look at the post you pointed early. Can you point me on the right direction, please?

**Comment by benjinus** [comment]
> @xiasenhai I need to use this functionality but I don't know where is placed. I am using the com.github.barteksc:android-pdf-viewer:3.2.0-beta.1 library. But this functionality is not there...I already take a look at the post you pointed early. Can you point me on the right direction, please?

I'm very sorry, I haven't been working on Android related development for several years. At present, my main job is in front-end development, and I may not be able to provide you with much assistance.

**Comment by FranzLiebkind0** [comment]
> @xiasenhai I need to use this functionality but I don't know where is placed. I am using the com.github.barteksc:android-pdf-viewer:3.2.0-beta.1 library. But this functionality is not there...I already take a look at the post you pointed early. Can you point me on the right direction, please?

@laurabarroso41 

I worked on it for a few days and finally got it to work, so I wanted to give more detail for anyone else looking for the answer

First step is to import mhiew/AndroidPdfViewer [3.2.0-beta.3](https://github.com/mhiew/AndroidPdfViewer/releases/tag/3.2.0-beta.3), but you will want to download as zip file to modify

In my build.gradle for the app, I commented out implementation 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.3' and instead entered implementation project(":android-pdf-viewer")


- In the build.gradle **for the imported android-pdf viewer**, I commented out api 'com.github.mhiew:pdfium-android:1.9.2' and instead added api 'com.github.Infomaniak:PdfiumAndroid:1.9.6'. It is important to use 1.9.6 as opposed to the latest version (1.9.8) because the latest version doesn't have the changes in PdfiumCore and mainJNILib.cpp described here:
https://github.com/barteksc/PdfiumAndroid/pull/46/commits

- In the PdfFile, I added the below method
```
public PointF mapDeviceCoordsToPage(int pageIndex, int startX, int startY, int sizeX, int sizeY,
                                        int deviceX, int deviceY) {
        int docPage = documentPage(pageIndex);
        return pdfiumCore.mapDeviceCoordsToPage(pdfDocument, docPage, startX, startY, sizeX, sizeY, 0, deviceX, deviceY);
    }
```

- In the PDFView file, I added the below method
```
public PointF convertScreenPointToPdfPagePoint(MotionEvent e) {
        float x = e.getX();
        float y = e.getY();

        if (pdfFile == null) {
            return null;
        }

        float mappedX = -getCurrentXOffset() + x;
        float mappedY = -getCurrentYOffset() + y;
        int page = pdfFile.getPageAtOffset(isSwipeVertical() ? mappedY : mappedX, getZoom());
        SizeF pageSize = pdfFile.getScaledPageSize(page, getZoom());
        int pageX, pageY;

        if (isSwipeVertical()) {
            pageX = (int) pdfFile.getSecondaryPageOffset(page, getZoom());
            pageY = (int) pdfFile.getPageOffset(page, getZoom());
        } else {
            pageY = (int) pdfFile.getSecondaryPageOffset(page, getZoom());
            pageX = (int) pdfFile.getPageOffset(page, getZoom());
        }

        return pdfFile.mapDeviceCoordsToPage(page, pageX, pageY, (int) pageSize.getWidth(),
                (int) pageSize.getHeight(), (int) mappedX, (int) mappedY);
    }
```

- Finally in my app activity, I call on the convertScreenPointToPdfPagePoint method inside an onTap listener (as part of the pdfview configuration i.e., .onTap(new onTapListener() {...convertScreenPointToPdfPagePoint...})

Hope this helps anyone looking to understand how to implement

**Pull request closed without merging**
